lib/pipeline-stack/index.ts, package.json
Temporarily suppressed deprecation warning for pipelines and upgraded to 0.12.3 of the core lib
=> Feature/upgrade 0.12.3

README.md, lib/bottlerocket-construct/index.ts, lib/custom-cluster-construct/index.ts, lib/fargate-construct/index.ts, lib/multi-region-construct/index.ts, lib/multi-team-construct/index.ts, lib/nginx-ingress-construct/index.ts, lib/pipeline-stack/index.ts, lib/scratchpad/index.ts, lib/teams/team-burnham/index.ts, lib/teams/team-burnham/restrict-ingress-egress-burnham.yaml, lib/teams/team-platform/index.ts, lib/teams/team-riker/index.ts, lib/teams/team-riker/restrict-ingress-egress-riker.yaml, package.json
- Added team manifests into teams directory and made changes to the blueprints to leverage them.
- Minor edits include upgrading npm module version under `package.json`.
- Addresses Issue #7 
- README edits to address incorrect links.
=> added team manifests; other minor edits

lib/keptn-construct/index.ts, lib/nginx-ingress-construct/index.ts, package.json
Fixing build and cdk list. Upgraded framework version.
=> fixing patterns to build and work

README.md
=> doc update fixing instructions

README.md, bin/main.ts, lib/newrelic-construct/index.ts, package.json
Adding New Relic addon pattern.
=> New Relic addon pattern

README.md, lib/dynatrace-construct/index.ts, package.json
Signed-off-by: Christian Heckelmann <christian.heckelmann@dynatrace.com>
Description of changes:
Adding Dynatrace Oneagent Pattern.
A Secrets Manager Secret is expected as described within the README.md file.
=> feat: Adding Dynatrace Oneagent pattern

README.md, bin/main.ts, lib/datadog-construct/index.ts, package.json
Adding Datadog pattern construct 
=> add datadog-construct

bin/main.ts, lib/common/construct-utils.ts, lib/datadog-construct/index.ts, lib/dynatrace-construct/index.ts, lib/nginx-ingress-construct/index.ts
=> Feature/datadog - async pattern with secret validation

README.md, package.json
*Description of changes:* upgraded to 1.0.0, overriding partner dependencies to blueprints 1.0.0 and cdk 2.20.0.
=> Task/upgrade to 1.0.0

bin/main.ts, lib/snyk-construct/index.ts, package.json
New pattern for the [Snyk addon](https://github.com/snyk-partners/snyk-monitor-eks-blueprints-addon).
=> Snyk addon pattern

bin/main.ts, lib/rafay-construct/index.ts, package.json
=> Example for Rafay Addon

bin/main.ts, lib/multi-region-construct/index.ts, lib/nginx-ingress-construct/index.ts, lib/rafay-construct/index.ts, package.json
Upgraded library and CDK to use the latest.
Multi-region pattern is using a cluster provider with enough nodes to acomodate for all pods.
=> Feature/upgrade 1.1.0

lib/bottlerocket-construct/index.ts, lib/fargate-construct/index.ts, lib/generic-cluster-construct/index.ts, lib/multi-region-construct/index.ts, lib/multi-team-construct/index.ts, lib/nginx-ingress-construct/index.ts, lib/pipeline-multi-env-gitops/index.ts, lib/pipeline-stack/index.ts, lib/teams/team-burnham/index.ts, package.json
=> upgraded to 1.2.0, replaced deprecated add-ons

lib/amp-monitoring/index.ts, lib/cloudwatch-monitoring/index.ts, lib/kubeflow-construct/index.ts, package.json
*Issue #, if available:* Adding new Kubestate metrics and prometheus node exporter to multi account pattern.
*Description of changes:* Adding new Kubestate metrics and prometheus node exporter to multi account pattern.
=> Adding new addons to Multi account pattern

docs/patterns/multi-account-monitoring.md
Adding cdk context instructions to multi mon
=> Adding cdk context instructions to multi mon

package.json
=> 1.5.2 upgrade

bin/main.ts, lib/emr-eks/index.ts, lib/teams/index.ts, lib/teams/team-emr-on-eks/index.ts, package.json
Add a pattern to show how to EMR on EKS AddOn.
=> add emr on eks pattern

docs/patterns/kubeflow.md, lib/kubeflow-construct/index.ts, package.json
Enhancing Open Source Monitoring to KubeFlow Construct.
=> Adding Monitoring to KubeFlow Construct

package.json
=> upgrading to 1.5.4

docs/patterns/secureingresscognito.md
=> Fixing Bug for SecretsManager for Kubecost pattern

lib/security/guardduty-construct/index.ts
Switching to buildAsync and adding the param to prevalidateSecrets
=> Switching to buildAsync and adding the param to prevalidateSecrets

docs/patterns/paralus.md, lib/paralus-construct/index.ts, package.json
Submitting new PR based on https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/63
=> Paralus eks blueprint

bin/main.ts, docs/patterns/paralus.md, lib/paralus-construct/index.ts, package.json
https://github.com/aws-quickstart/cdk-eks-blueprints/issues/580
Creates a sample eks blueprint for paralus addon
=> changes to add paralus addon to eks blueprint

lib/amp-monitoring/index.ts, lib/kubeflow-construct/index.ts, package.json
=> Amp Construction Configurations changes to Kubeflow and Multi Mon Patterns

docs/patterns/security/guardduty.md
Addressing the following feedback:
1. Instructions need to be clear on what settings to be enabled when GD is already enabled with hyperlink
2. Pre req should have instructions on npm I CDK bootstrap etc
3. Update kubeconfig instructions is missing
=> Updating the GuardDuty pattern documentation

docs/patterns/paralus.md
Fixing documentation that included AWS credentials
=> Paralus hotfix

bin/main.ts, lib/securityhub-construct/index.ts, lib/securityhub-construct/securityhub-setup.ts
EKS Blueprints SecurityHub Pattern
=> initial progress for securityhub pattern

bin/data-at-rest-encryption.ts, bin/dynatrace-operator.ts, bin/ecr-image-scanning.ts, bin/guardduty.ts, bin/pipeline-multienv-gitops.ts, bin/pipeline-multienv-monitoring.ts, bin/pipeline.ts, bin/secure-ingress-cognito.ts
Improved the error handling and messaging, stacks fail and give irrelevant errors
*Description of changes:* Improved the error handling and messaging, stacks fail and give irrelevant errors incase end user extends the stack and makes mistake in it. Generic error is shown which not relevant. Changed the code to add the error which will give user more feedback of actual cause of error.
=> Improved the error handling and messaging, stacks fail and give irrelevant errors

README.md, mkdocs.yml
=> mkdocs.yaml update

docs/patterns/secureingresscognito.md, lib/secure-ingress-auth-cognito/index.ts, lib/secure-ingress-auth-cognito/lambda/lambda_function.py
=> Fixing an issue HTTP request and Ingress with recent annotation changes

lib/secure-ingress-auth-cognito/lambda/lambda_function.py
Remove the email address auto approval so only users with a verified email address can login.
=> Remove auto approval in secure access

lib/secure-ingress-auth-cognito/lambda/lambda_function.py
With this change anyone from the allow-listed domain can sign-up and sign-in.
=> Remove auto allowed domains and allow-listed email addresses

docs/patterns/paralus.md
Addressing grammatical and punctuation issues
=> cleaning up Paralus docs

bin/instana-operator.ts, docs/patterns/instana.md, lib/instana-construct/index.ts, package.json
Added secretParamName to store Instana credentials.
- AWS Secret Impl to store Instana Addon Credentials.
- Modified Instana docs
=> AWS Secret Impl to store Instana Addon Credentials

docs/patterns/instana.md
=> Fixed typo in Disclaimer

bin/import-cluster.ts, lib/common/construct-utils.ts, lib/common/graviton-builder.ts, lib/graviton-construct/index.ts, lib/import-cluster/index.ts, lib/teams/team-troi/index.ts, package.json
=> Refreshing and Adding usage tracker to Graviton Pattern.

docs/patterns/multi-account-monitoring.md
=> added AWS_REGION and updated gitOwner

bin/karpenter.ts, docs/patterns/graviton.md, docs/patterns/karpenter.md, lib/karpenter-construct/index.ts
*Issue #, if available:* https://github.com/aws-quickstart/cdk-eks-blueprints/issues/764
*Description of changes:* Add a karpenter pattern and docs, fix graviton docs
=> Karpenter pattern

.github/workflows/e2e.yaml, ci/buildspec.yml
CI Pipeline for EKS Blueprints Patterns
=> CI Pipeline for EKS Blueprints Patterns

.github/workflows/e2e.yaml
=> switched to OIDC provider for github for codebuild access

.github/workflows/e2e.yaml
=> fixed variable for region resolution

mkdocs.yml
=> Update mkdocs.yml - missing Backstage Pattern

README.md, mkdocs.yml
=> Generative AI doc fix

docs/patterns/generative-ai/showcase.md
=> Generative AI doc fix image

lib/generative-ai-showcase/index.ts
Generative AI fix usage tracking
=> Generative AI fix usage tracking

docs/patterns/generative-ai/showcase.md
Minor doc corrections for gen-ai showcase walkthrough
=> Minor doc corrections for gen-ai showcase walkthrough

cdk.json, lib/generative-ai-showcase/deployment/showcase-deployment.ytpl, lib/generative-ai-showcase/index.ts
=> Gen AI Pattern Region Fix

docs/patterns/backstage.md
issue: image not present in here: https://aws-samples.github.io/cdk-eks-blueprints-patterns/patterns/backstage/
=> updated markdown of Backstage diagram in docs

lib/dynatrace-construct/index.ts, lib/rafay-construct/index.ts, package.json
Fixed partner patterns and outdated transitive dependencies.
=> Upgraded libraries, removed vulnerabilities, blueprints upgraded to 1.13.1

bin/komodor.ts, lib/backstage-construct/index.ts, lib/generic-cluster-construct/index.ts, lib/karpenter-construct/index.ts, lib/kubeflow-construct/index.ts, lib/security/data-at-rest-encryption/index.ts, lib/windows-construct/index.ts, package.json
=> Blueprints and Kubeflow Pattern Upgrade

.devcontainer/devcontainer.json, .devcontainer/postCreateCommand.sh, README.md, docs/patterns/kubeflow.md
Introducing Dev Containers to Patterns Repo
=> Introducing Dev Containers to Patterns Repo

.github/workflows/markdown-link-check.yaml, README.md
=> Fixing GH Action Error
